service: shop-react-redux-be
frameworkVersion: "3"

provider:
  name: aws
  runtime: nodejs14.x
  stage: dev
  region: eu-central-1

functions:
  getProductsList:
    handler: handlers/getProductsList.getProductsList
    events:
      - http:
          method: get
          path: /products
          cors: true
  getProductsById:
    handler: handlers/getProductsById.getProductsById
    events:
      - http:
          method: get
          path: /products/{productId}
          cors: true
